package com.example.turistguide.repository;


import com.example.turistguide.model.Tag;
import com.example.turistguide.model.TouristAttraction;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;

@Repository
public class TouristRepository {

    private final List<TouristAttraction> attractions;

    public TouristRepository() {

        attractions = new ArrayList<>();
        attractions.add(new TouristAttraction("Tivoli", "Forlystelsespark i København", "København", List.of(Tag.ADGANG_FOR_GANGBESVAEREDE, Tag.KONCERTHAL), 170));
        attractions.add(new TouristAttraction("Bakken", "Forlystelsespark i ydre København", "Klampenborg", List.of(Tag.ADGANG_FOR_GANGBESVAEREDE, Tag.GRATIS_INDGANG, Tag.KONCERTHAL, Tag.HUNDETILLADELSE), 0));
        attractions.add(new TouristAttraction("Djurs sommerland", "Danmarks bedste rutschebaner, det kæmpestore Vandland og over 60 sjove forlystelser for både små og store legebørn.", "Nimtofte", List.of(Tag.VANDLAND, Tag.HUNDETILLADELSE), 350));

    }

    public TouristAttraction addTouristAttraction(TouristAttraction touristAttraction) {

        if (touristAttraction.getDescription() == null) {
            touristAttraction.setDescription("Ingen oplysninger");
        }
        if (touristAttraction.getCity() == null) {
            touristAttraction.setCity("Ukendt Lokation");
        }

        attractions.add(touristAttraction);
        return touristAttraction;
    }

    public TouristAttraction findAttractionByName(String name) {
        for (TouristAttraction touristAttraction : attractions) {
            if (touristAttraction.getName().equalsIgnoreCase(name)) {
                return touristAttraction;
            }
        }
        return null;
    }

    public List<TouristAttraction> getAllTouristAttraction() {
        return attractions;
    }

    public TouristAttraction getTouristAttraction(String name) {
        return findAttractionByName(name);
    }

    public void updateTouristAttraction(TouristAttraction updatedTouristAttraction) {
        TouristAttraction touristAttraction = findAttractionByName(updatedTouristAttraction.getName());
        deleteTouristAttraction(touristAttraction.getName());

//        //check all attributes of TouristAttraction class for updated information
        if (updatedTouristAttraction.getDescription() != null) {
            touristAttraction.setDescription(updatedTouristAttraction.getDescription());
        }
        if (updatedTouristAttraction.getCity() != null) {
            touristAttraction.setCity(updatedTouristAttraction.getCity());
        }
        List<Tag> updatedTags = updatedTouristAttraction.getTags();
        if (updatedTags != null) { //TODO test denne condition
            touristAttraction.setTags(updatedTouristAttraction.getTags());
        }
        touristAttraction.setTicketPriceInDKK(updatedTouristAttraction.getTicketPriceInDKK());

        //resolve update
        attractions.add(touristAttraction);
    }

    public void deleteTouristAttraction(String name) {
        for (TouristAttraction touristAttraction : attractions) {
            if (touristAttraction.getName().equalsIgnoreCase(name)) {
                attractions.remove(touristAttraction);
                return;
            }
        }
    }

    public List<String> getCities() {
        return List.of(
                "Allinge",
                "Allingåbro",
                "Almind",
                "Anholt",
                "Ans By",
                "Ansager",
                "Arden",
                "Askeby",
                "Asnæs",
                "Asperup",
                "Assens",
                "Asaa",
                "Augustenborg",
                "Aulum",
                "Auning",
                "Bagenkop",
                "Bagsværd",
                "Balle",
                "Ballerup",
                "Bandholm",
                "Barrit",
                "Beder",
                "Bedsted Thy",
                "Bevtoft",
                "Billum",
                "Billund",
                "Bindslev",
                "Birkerød",
                "Bjerringbro",
                "Bjert",
                "Bjæverskov",
                "Blokhus",
                "Blommenslyst",
                "Blåvand",
                "Boeslunde",
                "Bogense",
                "Bogø By",
                "Bolderslev",
                "Bording",
                "Borre",
                "Borup",
                "Brabrand",
                "Bramming",
                "Brande",
                "Branderup",
                "Bredebro",
                "Bredsten",
                "Brenderup",
                "Broager",
                "Broby",
                "Brovst",
                "Bryrup",
                "Brædstrup",
                "Brøndby",
                "Brøndby Strand",
                "Brønderslev",
                "Brønshøj",
                "Brørup",
                "Bylderup Bov",
                "Bække",
                "Bækmarksbro",
                "Bælum",
                "Børkop",
                "Bøvlingbjerg",
                "Charlottenlund",
                "Christiansfeld",
                "Dalby",
                "Dalmose",
                "Dannemare",
                "Daugård",
                "Dianalund",
                "Dragør",
                "Dronninglund",
                "Dronningmølle",
                "Dybvad",
                "Ebberup",
                "Ebeltoft",
                "Egernsund",
                "Egtved",
                "Egå",
                "Ejby",
                "Ejstrupholm",
                "Engesvang",
                "Errindlev",
                "Erslev",
                "Esbjerg",
                "Eskebjerg",
                "Eskilstrup",
                "Espergærde",
                "Fakse",
                "Fakse Ladeplads",
                "Fanø",
                "Farsø",
                "Farum",
                "Fejø",
                "Ferritslev Fyn",
                "Fjenneslev",
                "Fjerritslev",
                "Flemming",
                "Fredensborg",
                "Fredericia",
                "Frederiksberg",
                "Frederikshavn",
                "Frederikssund",
                "Frederiksværk",
                "Frørup",
                "Frøstrup",
                "Fuglebjerg",
                "Fur",
                "Føllenslev",
                "Føvling",
                "Faaborg",
                "Fårevejle",
                "Fårup",
                "Fårvang",
                "Gadbjerg",
                "Gadstrup",
                "Galten",
                "Gandrup",
                "Gedser",
                "Gedsted",
                "Gedved",
                "Gelsted",
                "Gentofte",
                "Gesten",
                "Gilleleje",
                "Gislev",
                "Gislinge",
                "Gistrup",
                "Give",
                "Gjerlev",
                "Gjern",
                "Glamsbjerg",
                "Glejbjerg",
                "Glesborg",
                "Glostrup",
                "Glumsø",
                "Gram",
                "Gredstedbro",
                "Grenaa",
                "Greve",
                "Greve Strand",
                "Grevinge",
                "Grindsted",
                "Græsted",
                "Gråsten",
                "Gudbjerg",
                "Gudhjem",
                "Gudme",
                "Guldborg",
                "Gørding",
                "Gørlev",
                "Gørløse",
                "Haderslev",
                "Haderup",
                "Hadsten",
                "Hadsund",
                "Hagersten",
                "Hals",
                "Hammel",
                "Hampen",
                "Hanstholm",
                "Harboøre",
                "Harlev",
                "Harndrup",
                "Harpelunde",
                "Hasle",
                "Haslev",
                "Hasselager",
                "Havdrup",
                "Havndal",
                "Hedehusene",
                "Hedensted",
                "Hejls",
                "Hejnsvig",
                "Hellebæk",
                "Hellerup",
                "Helsinge",
                "Helsingør",
                "Hemmet",
                "Henne",
                "Herfølge",
                "Herlev",
                "Herlufmagle",
                "Herning",
                "Hesselager",
                "Hillerød",
                "Hinnerup",
                "Hirtshals",
                "Hjallerup",
                "Hjerm",
                "Hjortshøj",
                "Hjørring",
                "Hobro",
                "Holbæk",
                "Holeby",
                "Holme Olstrup",
                "Holstebro",
                "Holsted",
                "Holte",
                "Horbelev",
                "Hornbæk",
                "Hornslet",
                "Hornsyld",
                "Horsens",
                "Horslunde",
                "Hovborg",
                "Hovedgård",
                "Humble",
                "Humlebæk",
                "Hundested",
                "Hundslund",
                "Hurup Thy",
                "Hvalsø",
                "Hvide Sande",
                "Hvidovre",
                "Højbjerg",
                "Højby",
                "Højer",
                "Højslev",
                "Høng",
                "Hørning",
                "Hørsholm",
                "Hørve",
                "Haarby",
                "Hårlev",
                "Idestrup",
                "Ikast",
                "Ishøj",
                "Janderup",
                "Jelling",
                "Jerslev Vendsyssel",
                "Jerslev Sjælland",
                "Jerup",
                "Jordrup",
                "Juelsminde",
                "Jyderup",
                "Jyllinge",
                "Jystrup",
                "Jægerspris",
                "Kalundborg",
                "Kalvehave",
                "Karby",
                "Karise",
                "Karlslunde",
                "Karrebæksminde",
                "Karup",
                "Kastrup",
                "Kerteminde",
                "Kettinge",
                "Kibæk",
                "Kirke Eskilstrup",
                "Kirke Hyllinge",
                "Kirke Såby",
                "Kjellerup",
                "Klampenborg",
                "Klarup",
                "Klemensker",
                "Klippinge",
                "Klovborg",
                "Knebel",
                "Kokkedal",
                "Kolding",
                "Kolind",
                "Kongens Lyngby",
                "Kongerslev",
                "Korsør",
                "Kruså",
                "Kvistgård",
                "Kværndrup",
                "København",
                "Køge",
                "Langebæk",
                "Langeskov",
                "Langå",
                "Lejre",
                "Lem",
                "Lemming",
                "Lemvig",
                "Lille Skensved",
                "Lintrup",
                "Liseleje",
                "Lundby",
                "Lunderskov",
                "Lynge",
                "Lystrup",
                "Læsø",
                "Løgstrup",
                "Løgstør",
                "Løgumkloster",
                "Løkken",
                "Løsning",
                "Låsby",
                "Malling",
                "Mariager",
                "Maribo",
                "Marslev",
                "Marstal",
                "Martofte",
                "Melby",
                "Mern",
                "Mesinge",
                "Middelfart",
                "Millinge",
                "Morud",
                "Munke Bjergby",
                "Munkebo",
                "Møldrup",
                "Mørke",
                "Mørkøv",
                "Måløv",
                "Mårslet",
                "Nakskov",
                "Nexø",
                "Nibe",
                "Nimtofte",
                "Nivå",
                "Nordborg",
                "Nyborg",
                "Nykøbing F",
                "Nykøbing M",
                "Nykøbing Sj",
                "Nyrup",
                "Nysted",
                "Nærum",
                "Næstved",
                "Nørager",
                "Nørre Alslev",
                "Nørre Asmindrup",
                "Nørre Nebel",
                "Nørre Snede",
                "Nørre Aaby",
                "Nørreballe",
                "Nørresundby",
                "Odder",
                "Odense",
                "Oksbøl",
                "Otterup",
                "Oure",
                "Outrup",
                "Padborg",
                "Pandrup",
                "Præstø",
                "Randbøl",
                "Randers",
                "Ranum",
                "Rask Mølle",
                "Redsted",
                "Regstrup",
                "Ribe",
                "Ringe",
                "Ringkøbing",
                "Ringsted",
                "Risskov",
                "Roskilde",
                "Roslev",
                "Rude",
                "Rudkøbing",
                "Ruds Vedby",
                "Rungsted Kyst",
                "Ry",
                "Rynkeby",
                "Ryomgård",
                "Ryslinge",
                "Rødby",
                "Rødding",
                "Rødekro",
                "Rødkærsbro",
                "Rødovre",
                "Rødvig Stevns",
                "Rømø",
                "Rønde",
                "Rønne",
                "Rønnede",
                "Rørvig",
                "Sabro",
                "Sakskøbing",
                "Saltum",
                "Samsø",
                "Sandved",
                "Sejerø",
                "Silkeborg",
                "Sindal",
                "Sjællands Odde",
                "Sjølund",
                "Skagen",
                "Skals",
                "Skamby",
                "Skanderborg",
                "Skibby",
                "Skive",
                "Skjern",
                "Skodsborg",
                "Skovlunde",
                "Skælskør",
                "Skærbæk",
                "Skævinge",
                "Skødstrup",
                "Skørping",
                "Skårup",
                "Slagelse",
                "Slangerup",
                "Smørum",
                "Snedsted",
                "Snekkersten",
                "Snertinge",
                "Solbjerg",
                "Solrød Strand",
                "Sommersted",
                "Sorring",
                "Sorø",
                "Spenstrup",
                "Spjald",
                "Sporup",
                "Spøttrup",
                "Stakroge",
                "Stege",
                "Stenderup",
                "Stenlille",
                "Stenløse",
                "Stenstrup",
                "Stensved",
                "Stoholm",
                "Stokkemarke",
                "Store Fuglede",
                "Store Heddinge",
                "Store Merløse",
                "Storvorde",
                "Stouby",
                "Strandby",
                "Struer",
                "Strøby",
                "Stubbekøbing",
                "Støvring",
                "Suldrup",
                "Sulsted",
                "Sunds",
                "Svaneke",
                "Svebølle",
                "Svendborg",
                "Svenstrup",
                "Svinninge",
                "Sydals",
                "Sæby",
                "Søborg",
                "Søby ærø",
                "Søllested",
                "Sønder Felding",
                "Sønder Omme",
                "Sønder Stenderup",
                "Sønderborg",
                "Søndersø",
                "Sørvad",
                "Tappernøje",
                "Tarm",
                "Terndrup",
                "Them",
                "Thisted",
                "Thorsø",
                "Thyborøn",
                "Thyholm",
                "Tikøb",
                "Tilst",
                "Tim",
                "Tinglev",
                "Tistrup",
                "Tisvildeleje",
                "Tjele",
                "Tjæreborg",
                "Toftlund",
                "Tommerup",
                "Toreby",
                "Torrig",
                "Tranbjerg J",
                "Tranekær",
                "Trige",
                "Trustrup",
                "Tureby",
                "Tylstrup",
                "Tølløse",
                "Tønder",
                "Tørring",
                "Tårs",
                "Taastrup",
                "Ugerløse",
                "Uldum",
                "Ulfborg",
                "Ullerslev",
                "Ulstrup",
                "Vadum",
                "Valby",
                "Vallensbæk",
                "Vallensbæk Strand",
                "Vamdrup",
                "Vandel",
                "Vanløse",
                "Varde",
                "Vedbæk",
                "Veflinge",
                "Vejby",
                "Vejen",
                "Vejers Strand",
                "Vejle",
                "Vejle øst",
                "Vejstrup",
                "Veksø Sjælland",
                "Vemb",
                "Vemmelev",
                "Vesløs",
                "Vestbjerg",
                "Vester Skerninge",
                "Vesterborg",
                "Vestervig",
                "Viborg",
                "Viby J",
                "Viby Sjælland",
                "Videbæk",
                "Vig",
                "Vildbjerg",
                "Vils",
                "Vinderup",
                "Vipperød",
                "Virum",
                "Vissenbjerg",
                "Viuf",
                "Vodskov",
                "Vojens",
                "Vonge",
                "Vorbasse",
                "Vordingborg",
                "Vrå",
                "Væggerløse",
                "Værløse",
                "Ærøskøbing",
                "Ølgod",
                "Ølsted",
                "Ølstykke",
                "Ørbæk",
                "Ørnhøj",
                "Ørsted",
                "Ørum Djurs",
                "Østbirk",
                "Øster Assels",
                "Øster Ulslev",
                "Øster Vrå",
                "Østermarie",
                "Aabenrå",
                "Aabybro",
                "Åbyhøj",
                "Aakirkeby",
                "Aalborg",
                "Ålbæk",
                "Aalestrup",
                "Ålsgårde",
                "Århus",
                "Årre",
                "Aars",
                "Årslev",
                "Aarup",
                "Ukendt Lokation"
        );
    }

    public List<Tag> getTags() {
        return List.of(Tag.values());
    }

}
