package com.example.turistguide.repository;


import com.example.turistguide.model.Tag;
import com.example.turistguide.model.TouristAttraction;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;

@Repository
public class TouristRepository {

    private final List<TouristAttraction> attractions;

    public TouristRepository() {

        attractions = new ArrayList<>();
        attractions.add(new TouristAttraction("Tivoli", "Forlystelsespark i København", "København", List.of(Tag.ADGANG_FOR_GANGBESVAEREDE, Tag.KONCERTHAL)));
        attractions.add(new TouristAttraction("Bakken", "Forlystelsespark i ydre København", "Klampenborg", List.of(Tag.ADGANG_FOR_GANGBESVAEREDE, Tag.GRATIS_INDGANG, Tag.KONCERTHAL, Tag.HUNDETILLADELSE)));
        attractions.add(new TouristAttraction("Djurs sommerland", "Danmarks bedste rutschebaner, det kæmpestore Vandland og over 60 sjove forlystelser for både små og store legebørn.", "Nimtofte", List.of(Tag.VANDLAND, Tag.HUNDETILLADELSE)));

    }

    public TouristAttraction addTouristAttraction(TouristAttraction touristAttraction) {

        if (touristAttraction.getDescription() == null) {
            touristAttraction.setDescription("Ingen oplysninger");
        }
        if (touristAttraction.getCity() == null) {
            touristAttraction.setCity("Ukendt Lokation");
        }

        attractions.add(touristAttraction);
        return touristAttraction;
    }

    public TouristAttraction findAttractionByName(String name) {
        for (TouristAttraction touristAttraction : attractions) {
            if (touristAttraction.getName().equalsIgnoreCase(name)) {
                return touristAttraction;
            }
        }
        return null;
    }

    public List<TouristAttraction> getAllTouristAttraction() {
        return attractions;
    }

    public TouristAttraction getTouristAttraction(String name) {
        return findAttractionByName(name);
    }

    public void updateTouristAttraction(TouristAttraction updatedTouristAttraction) {
        TouristAttraction touristAttraction = findAttractionByName(updatedTouristAttraction.getName());
        deleteTouristAttraction(touristAttraction.getName());

//        //check all attributes of TouristAttraction class for updated information
        if (updatedTouristAttraction.getDescription() != null) {
            touristAttraction.setDescription(updatedTouristAttraction.getDescription());
        }
        if (updatedTouristAttraction.getCity() != null) {
            touristAttraction.setCity(updatedTouristAttraction.getCity());
        }
        List<Tag> updatedTags = updatedTouristAttraction.getTags();
        if (updatedTags != null) { //TODO test denne condition
            touristAttraction.setTags(updatedTouristAttraction.getTags());
        }

        //resolve update
        attractions.add(touristAttraction);
    }

    public void deleteTouristAttraction(String name) {
        for (TouristAttraction touristAttraction : attractions) {
            if (touristAttraction.getName().equalsIgnoreCase(name)) {
                attractions.remove(touristAttraction);
                return;
            }
        }
    }

    public List<String> getCities() {
        return List.of(
                "Allinge",
                "Allingaabro",
                "Almind",
                "Anholt",
                "Ans By",
                "Ansager",
                "Arden",
                "Askeby",
                "Asnaes",
                "Asperup",
                "Assens",
                "Asaa",
                "Augustenborg",
                "Aulum",
                "Auning",
                "Bagenkop",
                "Bagsvaerd",
                "Balle",
                "Ballerup",
                "Bandholm",
                "Barrit",
                "Beder",
                "Bedsted Thy",
                "Bevtoft",
                "Billum",
                "Billund",
                "Bindslev",
                "Birkeroed",
                "Bjerringbro",
                "Bjert",
                "Bjaeverskov",
                "Blokhus",
                "Blommenslyst",
                "Blaavand",
                "Boeslunde",
                "Bogense",
                "Bogoe By",
                "Bolderslev",
                "Bording",
                "Borre",
                "Borup",
                "Brabrand",
                "Bramming",
                "Brande",
                "Branderup",
                "Bredebro",
                "Bredsten",
                "Brenderup",
                "Broager",
                "Broby",
                "Brovst",
                "Bryrup",
                "Braedstrup",
                "Broendby",
                "Broendby Strand",
                "Broenderslev",
                "Broenshoej",
                "Broerup",
                "Bylderup Bov",
                "Baekke",
                "Baekmarksbro",
                "Baelum",
                "Boerkop",
                "Boevlingbjerg",
                "Charlottenlund",
                "Christiansfeld",
                "Dalby",
                "Dalmose",
                "Dannemare",
                "Daugaard",
                "Dianalund",
                "Dragoer",
                "Dronninglund",
                "Dronningmoelle",
                "Dybvad",
                "Ebberup",
                "Ebeltoft",
                "Egernsund",
                "Egtved",
                "Egaa",
                "Ejby",
                "Ejstrupholm",
                "Engesvang",
                "Errindlev",
                "Erslev",
                "Esbjerg",
                "Eskebjerg",
                "Eskilstrup",
                "Espergaerde",
                "Fakse",
                "Fakse Ladeplads",
                "Fanoe",
                "Farsoe",
                "Farum",
                "Fejoe",
                "Ferritslev Fyn",
                "Fjenneslev",
                "Fjerritslev",
                "Flemming",
                "Fredensborg",
                "Fredericia",
                "Frederiksberg",
                "Frederikshavn",
                "Frederikssund",
                "Frederiksvaerk",
                "Froerup",
                "Froestrup",
                "Fuglebjerg",
                "Fur",
                "Foellenslev",
                "Foevling",
                "Faaborg",
                "Faarevejle",
                "Faarup",
                "Faarvang",
                "Gadbjerg",
                "Gadstrup",
                "Galten",
                "Gandrup",
                "Gedser",
                "Gedsted",
                "Gedved",
                "Gelsted",
                "Gentofte",
                "Gesten",
                "Gilleleje",
                "Gislev",
                "Gislinge",
                "Gistrup",
                "Give",
                "Gjerlev",
                "Gjern",
                "Glamsbjerg",
                "Glejbjerg",
                "Glesborg",
                "Glostrup",
                "Glumsoe",
                "Gram",
                "Gredstedbro",
                "Grenaa",
                "Greve",
                "Greve Strand",
                "Grevinge",
                "Grindsted",
                "Graested",
                "Graasten",
                "Gudbjerg",
                "Gudhjem",
                "Gudme",
                "Guldborg",
                "Goerding",
                "Goerlev",
                "Goerloese",
                "Haderslev",
                "Haderup",
                "Hadsten",
                "Hadsund",
                "Hagersten",
                "Hals",
                "Hammel",
                "Hampen",
                "Hanstholm",
                "Harbooere",
                "Harlev",
                "Harndrup",
                "Harpelunde",
                "Hasle",
                "Haslev",
                "Hasselager",
                "Havdrup",
                "Havndal",
                "Hedehusene",
                "Hedensted",
                "Hejls",
                "Hejnsvig",
                "Hellebaek",
                "Hellerup",
                "Helsinge",
                "Helsingoer",
                "Hemmet",
                "Henne",
                "Herfoelge",
                "Herlev",
                "Herlufmagle",
                "Herning",
                "Hesselager",
                "Hilleroed",
                "Hinnerup",
                "Hirtshals",
                "Hjallerup",
                "Hjerm",
                "Hjortshoej",
                "Hjoerring",
                "Hobro",
                "Holbaek",
                "Holeby",
                "Holme Olstrup",
                "Holstebro",
                "Holsted",
                "Holte",
                "Horbelev",
                "Hornbaek",
                "Hornslet",
                "Hornsyld",
                "Horsens",
                "Horslunde",
                "Hovborg",
                "Hovedgaard",
                "Humble",
                "Humlebaek",
                "Hundested",
                "Hundslund",
                "Hurup Thy",
                "Hvalsoe",
                "Hvide Sande",
                "Hvidovre",
                "Hoejbjerg",
                "Hoejby",
                "Hoejer",
                "Hoejslev",
                "Hoeng",
                "Hoerning",
                "Hoersholm",
                "Hoerve",
                "Haarby",
                "Haarlev",
                "Idestrup",
                "Ikast",
                "Ishoej",
                "Janderup",
                "Jelling",
                "Jerslev Vendsyssel",
                "Jerslev Sjaelland",
                "Jerup",
                "Jordrup",
                "Juelsminde",
                "Jyderup",
                "Jyllinge",
                "Jystrup",
                "Jaegerspris",
                "Kalundborg",
                "Kalvehave",
                "Karby",
                "Karise",
                "Karlslunde",
                "Karrebaeksminde",
                "Karup",
                "Kastrup",
                "Kerteminde",
                "Kettinge",
                "Kibaek",
                "Kirke Eskilstrup",
                "Kirke Hyllinge",
                "Kirke Saaby",
                "Kjellerup",
                "Klampenborg",
                "Klarup",
                "Klemensker",
                "Klippinge",
                "Klovborg",
                "Knebel",
                "Kokkedal",
                "Kolding",
                "Kolind",
                "Kongens Lyngby",
                "Kongerslev",
                "Korsoer",
                "Krusaa",
                "Kvistgaard",
                "Kvaerndrup",
                "Koebenhavn",
                "Koege",
                "Langebaek",
                "Langeskov",
                "Langaa",
                "Lejre",
                "Lem",
                "Lemming",
                "Lemvig",
                "Lille Skensved",
                "Lintrup",
                "Liseleje",
                "Lundby",
                "Lunderskov",
                "Lynge",
                "Lystrup",
                "Laesoe",
                "Loegstrup",
                "Loegstoer",
                "Loegumkloster",
                "Loekken",
                "Loesning",
                "Laasby",
                "Malling",
                "Mariager",
                "Maribo",
                "Marslev",
                "Marstal",
                "Martofte",
                "Melby",
                "Mern",
                "Mesinge",
                "Middelfart",
                "Millinge",
                "Morud",
                "Munke Bjergby",
                "Munkebo",
                "Moeldrup",
                "Moerke",
                "Moerkoev",
                "Maaloev",
                "Maarslet",
                "Nakskov",
                "Nexoe",
                "Nibe",
                "Nimtofte",
                "Nivaa",
                "Nordborg",
                "Nyborg",
                "Nykoebing F",
                "Nykoebing M",
                "Nykoebing Sj",
                "Nyrup",
                "Nysted",
                "Naerum",
                "Naestved",
                "Noerager",
                "Noerre Alslev",
                "Noerre Asmindrup",
                "Noerre Nebel",
                "Noerre Snede",
                "Noerre Aaby",
                "Noerreballe",
                "Noerresundby",
                "Odder",
                "Odense",
                "Oksboel",
                "Otterup",
                "Oure",
                "Outrup",
                "Padborg",
                "Pandrup",
                "Praestoe",
                "Randboel",
                "Randers",
                "Ranum",
                "Rask Moelle",
                "Redsted",
                "Regstrup",
                "Ribe",
                "Ringe",
                "Ringkoebing",
                "Ringsted",
                "Risskov",
                "Roskilde",
                "Roslev",
                "Rude",
                "Rudkoebing",
                "Ruds Vedby",
                "Rungsted Kyst",
                "Ry",
                "Rynkeby",
                "Ryomgaard",
                "Ryslinge",
                "Roedby",
                "Roedding",
                "Roedekro",
                "Roedkaersbro",
                "Roedovre",
                "Roedvig Stevns",
                "Roemoe",
                "Roende",
                "Roenne",
                "Roennede",
                "Roervig",
                "Sabro",
                "Sakskoebing",
                "Saltum",
                "Samsoe",
                "Sandved",
                "Sejeroe",
                "Silkeborg",
                "Sindal",
                "Sjaellands Odde",
                "Sjoelund",
                "Skagen",
                "Skals",
                "Skamby",
                "Skanderborg",
                "Skibby",
                "Skive",
                "Skjern",
                "Skodsborg",
                "Skovlunde",
                "Skaelskoer",
                "Skaerbaek",
                "Skaevinge",
                "Skoedstrup",
                "Skoerping",
                "Skaarup",
                "Slagelse",
                "Slangerup",
                "Smoerum",
                "Snedsted",
                "Snekkersten",
                "Snertinge",
                "Solbjerg",
                "Solroed Strand",
                "Sommersted",
                "Sorring",
                "Soroe",
                "Spenstrup",
                "Spjald",
                "Sporup",
                "Spoettrup",
                "Stakroge",
                "Stege",
                "Stenderup",
                "Stenlille",
                "Stenloese",
                "Stenstrup",
                "Stensved",
                "Stoholm",
                "Stokkemarke",
                "Store Fuglede",
                "Store Heddinge",
                "Store Merloese",
                "Storvorde",
                "Stouby",
                "Strandby",
                "Struer",
                "Stroeby",
                "Stubbekoebing",
                "Stoevring",
                "Suldrup",
                "Sulsted",
                "Sunds",
                "Svaneke",
                "Sveboelle",
                "Svendborg",
                "Svenstrup",
                "Svinninge",
                "Sydals",
                "Saeby",
                "Soeborg",
                "Soeby Aeroe",
                "Soellested",
                "Soender Felding",
                "Soender Omme",
                "Soender Stenderup",
                "Soenderborg",
                "Soendersoe",
                "Soervad",
                "Tappernoeje",
                "Tarm",
                "Terndrup",
                "Them",
                "Thisted",
                "Thorsoe",
                "Thyboroen",
                "Thyholm",
                "Tikoeb",
                "Tilst",
                "Tim",
                "Tinglev",
                "Tistrup",
                "Tisvildeleje",
                "Tjele",
                "Tjaereborg",
                "Toftlund",
                "Tommerup",
                "Toreby",
                "Torrig",
                "Tranbjerg J",
                "Tranekaer",
                "Trige",
                "Trustrup",
                "Tureby",
                "Tylstrup",
                "Toelloese",
                "Toender",
                "Toerring",
                "Taars",
                "Taastrup",
                "Ugerloese",
                "Uldum",
                "Ulfborg",
                "Ullerslev",
                "Ulstrup",
                "Vadum",
                "Valby",
                "Vallensbaek",
                "Vallensbaek Strand",
                "Vamdrup",
                "Vandel",
                "Vanloese",
                "Varde",
                "Vedbaek",
                "Veflinge",
                "Vejby",
                "Vejen",
                "Vejers Strand",
                "Vejle",
                "Vejle Oest",
                "Vejstrup",
                "Veksoe Sjaelland",
                "Vemb",
                "Vemmelev",
                "Vesloes",
                "Vestbjerg",
                "Vester Skerninge",
                "Vesterborg",
                "Vestervig",
                "Viborg",
                "Viby J",
                "Viby Sjaelland",
                "Videbaek",
                "Vig",
                "Vildbjerg",
                "Vils",
                "Vinderup",
                "Vipperoed",
                "Virum",
                "Vissenbjerg",
                "Viuf",
                "Vodskov",
                "Vojens",
                "Vonge",
                "Vorbasse",
                "Vordingborg",
                "Vraa",
                "Vaeggerloese",
                "Vaerloese",
                "Aeroeskoebing",
                "Oelgod",
                "Oelsted",
                "Oelstykke",
                "Oerbaek",
                "Oernhoej",
                "Oersted",
                "Oerum Djurs",
                "Oestbirk",
                "Oester Assels",
                "Oester Ulslev",
                "Oester Vraa",
                "Oestermarie",
                "Aabenraa",
                "Aabybro",
                "Aabyhoej",
                "Aakirkeby",
                "Aalborg",
                "Aalbaek",
                "Aalestrup",
                "Aalsgaarde",
                "Aarhus",
                "Aarre",
                "Aars",
                "Aarslev",
                "Aarup",
                "Ukendt Lokation"
        );
    }

    public List<Tag> getTags() {
        return List.of(Tag.values());
    }

}
